# Generated by Django 6.0.1 on 2026-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='_', max_length=10),
            preserve_default=False,
        ),
    ]
