# Generated by Django 6.0.2 on 2026-02-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_options_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
